version: '2'
services:
  server1:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site:/usr/share/nginx/html
      - ./nginx/my-site.com.crt:/etc/nginx/my-nginx.com.crt 
      - ./nginx/my-site.com.key:/etc/nginx/my-nginx.com.key 
    ports:
    - "8080:80"
    - "8443:443" 
  server2:
    image: httpd:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./site2:/usr/local/apache2/htdocs
      - ./apache/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ./apache/my-apache.com.crt:/usr/local/apache2/conf/server.crt
      - ./apache/my-apache.com.key:/usr/local/apache2/conf/server.key
